version: "3.8"

services:
  socket-server:
    build:
      context: .
    image: asia-northeast1-docker.pkg.dev/term-ai-427821/ttychat-server-artifacts/ttychat-server-image:latest
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 3000:3000
