name: CI

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'pnpm'
        cache-dependency-path: cli/pnpm-lock.yaml
    - run: cd cli && pnpm install --frozen-lockfile
    - run: cd cli && pnpm run build
